### ISSUE TITLE
Use nq_memparse instead of nq_parse

### ISSUE THREAD

**Issue by fasterthanlime** [fasterthanlime/cork#4]
It's just faster, and .ooc files aren't gigabytes large anyway..

(And to naysayers: if they were, the nagaqueen-based parser might work but the AST will _definitely_ blow up).

**Comment by vendethiel** [comment]
.oO( the naysayers versus the nagasayers )

(sorry, I just don't know what's the difference :P)

**Comment by fasterthanlime** [comment]
@vendethiel eeeeeh there's just always skeptics, even if they're just in my head. Gotta adopt all viewpoints to convince myself :) Those issues are documentation mostly
